"""update field name

Revision ID: 4ec71325a3db
Revises: fe7b2bacfa4a
Create Date: 2024-02-05 20:41:30.745682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils



# revision identifiers, used by Alembic.
revision: str = '4ec71325a3db'
down_revision: Union[str, None] = 'fe7b2bacfa4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('price', sa.Numeric(), nullable=False))
    op.drop_column('product', 'cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('cost', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('product', 'price')
    # ### end Alembic commands ###
